version: "3.8"
services:
  front-end:
    image: 
    ports:
    - 3000:3000
    depends_on:
    - back-end
  back-end:
    image:
    ports:
    - 50000:5000
    environment:
      - MONGO_URI: mongodb://Srinidhi101:Srinidhi2000@mongo:27017/notebookdb?authSource=notebookdb
      - JWT_SECRET: thisisthemostsecureserver
    depends_on:
    - mongo
  mongo:
    